Hw1 project4
PUArallelepiped/POSIXat pull request #1
Opened 2024-03-21 02:17 UTC by OuChiaYun

不確定提交檔案的要求是不是這樣子，沒有放.ko
盡量寫了點文件

2024-03-21 06:34 UTC, nonorze-VOXX reviewed
if remove .vs can it work?
y -> add .vs to gitignore

2024-03-21 06:35 UTC, nonorze-VOXX commented on project_4/part1/Makefile
> +kernel_DIR:= /usr/src/linux-headers-5.4.0-148-generic/
maybe can ref #2

2024-03-21 07:35 UTC, x06lan requested changes

2024-03-21 07:35 UTC, x06lan commented on project_4/part1/Makefile
> +kernel_DIR:= /usr/src/linux-headers-5.4.0-148-generic/
avoid use hardcode path
consider use $(shell uname -r)

2024-03-21 07:35 UTC, x06lan commented on .vs/POSIXat/v15/.suo
remove this

2024-03-21 07:35 UTC, x06lan commented on .vs/VSWorkspaceState.json
remove this

2024-03-21 07:35 UTC, x06lan commented on project_4/part2/Makefile
> +kernel_DIR:= /usr/src/linux-headers-5.4.0-148-generic/
same

2024-03-21 11:45 UTC, OuChiaYun commented on project_4/part1/Makefile
> +kernel_DIR:= /usr/src/linux-headers-5.4.0-148-generic/
done

2024-03-21 11:45 UTC, OuChiaYun commented on .vs/POSIXat/v15/.suo
done

2024-03-21 11:46 UTC, OuChiaYun commented
> if remove .vs can it work? y -> add .vs to gitignore

done, add .gitignore and add rm .vs

2024-03-21 11:46 UTC, OuChiaYun commented on project_4/part2/Makefile
> +kernel_DIR:= /usr/src/linux-headers-5.4.0-148-generic/
done

2024-03-21 11:47 UTC, OuChiaYun commented on .vs/VSWorkspaceState.json
done, use .gitignore and rm .vs

2024-03-22 06:36 UTC, x06lan approved these changes

2024-03-22 06:37 UTC, merged