Hw3 ch9
PUArallelepiped/POSIXat pull request #29
Opened 2024-05-06 13:02 UTC by OuChiaYun

2024-05-06 13:08 UTC, huhuhu0420 commented
you delete your code 🧐

2024-05-06 13:21 UTC, OuChiaYun commented
> you delete your code 🧐

笑鼠 我發現了orz

2024-05-06 17:14 UTC, huhuhu0420 requested changes
![image](https://github.com/PUArallelepiped/POSIXat/assets/94506311/d6bcacce-557a-4bea-b58f-348d1b8b98ba)

理論上不會有這種情況，release的時候就應該把連續unused的合在一起

然後compaction的時候會把所有unused的位置合併成一個
> your program will compact the set of holes
into one larger hole.

compaction完應該變成：
0:15 p1
16:199 unused

2024-05-06 17:15 UTC, huhuhu0420 commented
然後`ch9`資料夾放到`hw3`裡，可以的話rename成`9`比較統一

2024-05-06 17:24 UTC, OuChiaYun commented
> ![image](https://private-user-images.githubusercontent.com/94506311/328259473-d6bcacce-557a-4bea-b58f-348d1b8b98ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwMTY1NjgsIm5iZiI6MTcxNTAxNjI2OCwicGF0aCI6Ii85NDUwNjMxMS8zMjgyNTk0NzMtZDZiY2FjY2UtNTU3YS00YmVhLWI1OGYtMzQ4ZDFiOGI5OGJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDE3MjQyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0YWI1YWU5YTZmMjcwMWEyMGU0NmZiMDBjNDI4ZDUwMDk5ZjM3ZmEwNTliNzFiYTExY2UwOGQ2ZDA5MjQ1YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LLWXOlSSa10l4_YWAVq68VCiFD5P00cohL-QXpqUHQI)
> 
> 理論上不會有這種情況，release的時候就應該把連續unused的合在一起
> 
> 然後compaction的時候會把所有unused的位置合併成一個
> 
> > your program will compact the set of holes
> > into one larger hole.
> 
> compaction完應該變成： 0:15 p1 16:199 unused

了解 是我搞錯了
我想一下怎麼改

2024-05-06 18:59 UTC, OuChiaYun commented
> 然後`ch9`資料夾放到`hw3`裡，可以的話rename成`9`比較統一

done

2024-05-06 19:00 UTC, OuChiaYun commented
> ![image](https://private-user-images.githubusercontent.com/94506311/328259473-d6bcacce-557a-4bea-b58f-348d1b8b98ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwMjIyNjksIm5iZiI6MTcxNTAyMTk2OSwicGF0aCI6Ii85NDUwNjMxMS8zMjgyNTk0NzMtZDZiY2FjY2UtNTU3YS00YmVhLWI1OGYtMzQ4ZDFiOGI5OGJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDE4NTkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3MjJhMGQxODcyMDZkM2E5ZDM2MWI3YzY5YjZhNDUzM2QwM2U5ZTA2MmY3ZmRkNWEwMzhhYWQ1YzNkZTU5NjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M2e78a1Nzfi6URf35caLvg2vXsIHwgrNPZY0zjZHRKI)
> 
> 理論上不會有這種情況，release的時候就應該把連續unused的合在一起
> 
> 然後compaction的時候會把所有unused的位置合併成一個
> 
> > your program will compact the set of holes
> > into one larger hole.
> 
> compaction完應該變成： 0:15 p1 16:199 unused

done

2024-05-07 01:22 UTC, huhuhu0420 commented on hw3/9.p1/allocate.c
> +
```suggestion
if (argc != 2)
{
    fprintf(stderr, "Usage: %s <memory size>\n", argv[0]);
    return 1;
}
```

2024-05-07 01:23 UTC, huhuhu0420 commented
`ch9`的資料夾還是在欸

2024-05-07 05:06 UTC, huhuhu0420 approved these changes

2024-05-07 09:58 UTC, OuChiaYun commented on hw3/9.p1/allocate.c
> +
done

2024-05-07 09:58 UTC, OuChiaYun commented
> `ch9`的資料夾還是在欸

sor 我沒刪到，更新了

2024-05-07 13:21 UTC, x06lan approved these changes
not important
![screenshot-2024-05-07-21-05-09](https://github.com/PUArallelepiped/POSIXat/assets/52856456/d0c3a458-9a86-440f-9162-adb1fde6b2ab)

2024-05-07 13:23 UTC, nonorze-VOXX approved these changes

2024-05-07 13:23 UTC, merged